### ISSUE TITLE
Feature request: save file

### ISSUE THREAD

**Issue by OliverSchmitt** [trsvchn/coco-viewer#1]
This is a nice and simple viewer for the coco annotations. It would be nice if there was an option to save the file when looking at them.

**Comment by trsvchn** [comment]
@OliverSchmitt Thank you for your interest and feature request! I like your idea!) I didn't work on this app for a long time. But I think I can find some free time on this weekend to improve the viewer. Stay tuned! :)

**Comment by trsvchn** [comment]
Sorry, your issue was closed automatically because of merging.

**Comment by trsvchn** [comment]
@OliverSchmitt I hope this is what are looking for. Currently you can save composed files with `File -> Save` Menu as `png` file, but I am going to add a shortcut for that. But I think it is a good start.
