### ISSUE TITLE
Needed to install DejaVuSans.ttf

### ISSUE THREAD

**Issue by chrishardenunity** [trsvchn/coco-viewer#62]
To get this script to work, I needed to add DejaVuSans.ttf to the coco-viewer directory.  I dropped it in both the root and the assets directory.  The script did not find it after I installed on Windows, and my conda environment did not have it by default.  

I downloaded it from here: https://www.fontsquirrel.com/fonts/dejavu-sans

Thank you for the script!

**Comment by trsvchn** [comment]
@chrishardenunity Thank you! yes, it is a known issue, sorry for that.
