### ISSUE TITLE
KeyError: 'iscrowd'

### ISSUE THREAD

**Issue by norton-chris** [trsvchn/coco-viewer#63]
Hi,
I am getting this error when I run coco-viewer.

`(base) chris@Chriss-MacBook-Pro coco-viewer % python cocoviewer.py -i /Users/chris/Documents/video_frames/2022-07-22/Over -a /Users/chris/Downloads/test.json
INFO: Starting...
INFO: Parsing /Users/chris/Downloads/test.json...
Traceback (most recent call last):
  File "/Users/chris/Documents/coco-viewer/cocoviewer.py", line 821, in <module>
    main()
  File "/Users/chris/Documents/coco-viewer/cocoviewer.py", line 816, in main
    Controller(data, root, image_panel, statusbar, menu, objects_panel, sliders)
  File "/Users/chris/Documents/coco-viewer/cocoviewer.py", line 514, in __init__
    self.update_img()
  File "/Users/chris/Documents/coco-viewer/cocoviewer.py", line 573, in update_img
    self.compose_image(
  File "/Users/chris/Documents/coco-viewer/cocoviewer.py", line 542, in compose_image
    draw_masks(draw, objects, names_colors, ignore, alpha)
  File "/Users/chris/Documents/coco-viewer/cocoviewer.py", line 200, in draw_masks
    elif isinstance(m, dict) and objects[i]["iscrowd"]:
KeyError: 'iscrowd'
(base) chris@Chriss-MacBook-Pro coco-viewer % `

I am just trying out this tool to view my masks. This specific example I'm looking at one image. Since I can't attach json files, I attached a txt file, that I copied and pasted from the json file.
[test_json.txt](https://github.com/trsvchn/coco-viewer/files/9410514/test_json.txt)

I'm running this on MacOS Monterey on the M1 chip.

Any help would be greatly appreciated.
Thanks

**Comment by trsvchn** [comment]
Hi @norton-chris!

Thank you for your question!

In the txt file i've noticed a typo in it: `is_crowd`, it has to be without underscore: `iscrowd`.

Here see the COCO annotation format:

```json
annotation {
  "id" : int,
  "image_id" : int,
  "category_id" : int,
  "segmentation" : RLE or [polygon],
  "area" : float,
  "bbox" : [x,y,width,height],
"iscrowd" : 0 or 1,
}
```

**Comment by norton-chris** [comment]
Thank you! That fixed the issue, didn't even notice the typo. I used a coco json converter, so I'll have to see if that's what messed up that.
